# # preload = /home/pebble/Pictures/Wallpapers/demon_mode.jpg
# # wallpaper = eDP-1,/home/pebble/Pictures/Wallpapers/demon_mode.jpg
# # splash = false
#
# wallpaper {
#     #monitor = HDMI-A-3
#     monitor = 
#     path = /home/pebble/Pictures/Wallpapers/demon_mode.jpg
#     fit_mode = cover
# }
# splash = false
# ipc = false
